# Generated by Django 2.2.7 on 2020-01-16 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=250, null=True, verbose_name='имя')),
                ('lastname', models.CharField(max_length=250, null=True, verbose_name='фамилия')),
                ('born_data', models.CharField(max_length=250, null=True, verbose_name='день рождения')),
                ('skype', models.CharField(max_length=250, null=True, verbose_name='скайп')),
                ('text', models.TextField(null=True, verbose_name='о себе')),
                ('fb', models.URLField(null=True, verbose_name='ccылка на соц сети')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль',
                'verbose_name_plural': 'Профиль',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, null=True, verbose_name='заголовок')),
                ('text', models.TextField(null=True, verbose_name='текст')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='дата создания')),
                ('to_show', models.BooleanField(default=True, null=True, verbose_name='отображать?')),
                ('slug', models.SlugField(max_length=100, null=True, unique=True, verbose_name='url')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('is_readed', models.BooleanField(default=False, verbose_name='прочитано')),
                ('reciver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inmassages', to=settings.AUTH_USER_MODEL, verbose_name='получатель')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='outmassages', to=settings.AUTH_USER_MODEL, verbose_name='отправитель')),
            ],
            options={
                'verbose_name': 'Cообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='текст')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='дата создания')),
                ('to_show', models.BooleanField(default=False, verbose_name='отображать?')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='simpleblog.Post', verbose_name='пост')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
